#pragma once
#include <math.h>
#include <iostream>
#include <glm\glm.hpp>
#include <glm\ext.hpp>

namespace AFMaths
{
    class Vector2;
    class Vector3;

    class Vector4
    {
    public:
        // variables
        union
        {
            struct
            {
                float v[4];
            };
            struct
            {
                float x;
                float y;
                float z;
                float w;
            };
            struct
            {
                float r;
                float g;
                float b;
                float a;
            };
        };

        // constructors and destructor
        Vector4();
        Vector4(const float& value);
        Vector4(float newX, float newY, float newZ, float newW);
        Vector4(const Vector2& newVector);
        Vector4(const Vector3& newVector);
        Vector4(const Vector4& newVector);
        ~Vector4();

        // functions
        float dot(Vector4& rhs);
        Vector4 cross(Vector4& rhs);
        float magnitude();
        float squaremagnitude();
        void normalise();
        Vector4 normalized();
        glm::vec4 toGLM();
        glm::vec3 toGLM3();

        // shortcuts
        static Vector4 Up();
        static Vector4 Down();
        static Vector4 Left();
        static Vector4 Right();
        static Vector4 Forward();
        static Vector4 Back();
        static Vector4 Zero();

        // overloads
        friend std::ostream& operator << (std::ostream& stream, const Vector4& vector);
        operator float *();
        float& operator [] (const int& index);
        bool operator == (const Vector4& rhs);
        void operator = (const Vector2& newVector);
        void operator = (const Vector3& newVector);
        void operator = (const Vector4& newVector);
        Vector4 operator + (const Vector4& rhs);
        void operator += (const Vector4& rhs);
        Vector4 operator - (const Vector4& rhs);
        void operator -= (const Vector4& rhs);
        Vector4 operator * (const Vector4& rhs);
        void operator *= (const Vector4& rhs);
        Vector4 operator * (const float& scalar);
        void operator *= (const float& scalar);
        friend Vector4 operator * (const float& scalar, Vector4& vector);
        Vector4 operator / (const float& scalar);
        void operator /= (const float& scalar);

        // swizzling
        Vector2 GetXX();
        Vector2 GetXY();
        Vector2 GetXZ();
        Vector2 GetXW();
        Vector2 GetYX();
        Vector2 GetYY();
        Vector2 GetYZ();
        Vector2 GetYW();
        Vector2 GetZX();
        Vector2 GetZY();
        Vector2 GetZZ();
        Vector2 GetZW();
        Vector2 GetWX();
        Vector2 GetWY();
        Vector2 GetWZ();
        Vector2 GetWW();

        Vector3 GetXXX();
        Vector3 GetXXY();
        Vector3 GetXXZ();
        Vector3 GetXXW();
        Vector3 GetXYX();
        Vector3 GetXYY();
        Vector3 GetXYZ();
        Vector3 GetXYW();
        Vector3 GetXZX();
        Vector3 GetXZY();
        Vector3 GetXZZ();
        Vector3 GetXZW();
        Vector3 GetXWX();
        Vector3 GetXWY();
        Vector3 GetXWZ();
        Vector3 GetXWW();
        Vector3 GetYXX();
        Vector3 GetYXY();
        Vector3 GetYXZ();
        Vector3 GetYXW();
        Vector3 GetYYX();
        Vector3 GetYYY();
        Vector3 GetYYZ();
        Vector3 GetYYW();
        Vector3 GetYZX();
        Vector3 GetYZY();
        Vector3 GetYZZ();
        Vector3 GetYZW();
        Vector3 GetYWX();
        Vector3 GetYWY();
        Vector3 GetYWZ();
        Vector3 GetYWW();
        Vector3 GetZXX();
        Vector3 GetZXY();
        Vector3 GetZXZ();
        Vector3 GetZXW();
        Vector3 GetZYX();
        Vector3 GetZYY();
        Vector3 GetZYZ();
        Vector3 GetZYW();
        Vector3 GetZZX();
        Vector3 GetZZY();
        Vector3 GetZZZ();
        Vector3 GetZZW();
        Vector3 GetZWX();
        Vector3 GetZWY();
        Vector3 GetZWZ();
        Vector3 GetZWW();
        Vector3 GetWXX();
        Vector3 GetWXY();
        Vector3 GetWXZ();
        Vector3 GetWXW();
        Vector3 GetWYX();
        Vector3 GetWYY();
        Vector3 GetWYZ();
        Vector3 GetWYW();
        Vector3 GetWZX();
        Vector3 GetWZY();
        Vector3 GetWZZ();
        Vector3 GetWZW();
        Vector3 GetWWX();
        Vector3 GetWWY();
        Vector3 GetWWZ();
        Vector3 GetWWW();

        Vector4 GetXXXX();
        Vector4 GetXXXY();
        Vector4 GetXXXZ();
        Vector4 GetXXXW();
        Vector4 GetXXYX();
        Vector4 GetXXYY();
        Vector4 GetXXYZ();
        Vector4 GetXXYW();
        Vector4 GetXXZX();
        Vector4 GetXXZY();
        Vector4 GetXXZZ();
        Vector4 GetXXZW();
        Vector4 GetXXWX();
        Vector4 GetXXWY();
        Vector4 GetXXWZ();
        Vector4 GetXXWW();
        Vector4 GetXYXX();
        Vector4 GetXYXY();
        Vector4 GetXYXZ();
        Vector4 GetXYXW();
        Vector4 GetXYYX();
        Vector4 GetXYYY();
        Vector4 GetXYYZ();
        Vector4 GetXYYW();
        Vector4 GetXYZX();
        Vector4 GetXYZY();
        Vector4 GetXYZZ();
        Vector4 GetXYWX();
        Vector4 GetXYWY();
        Vector4 GetXYWZ();
        Vector4 GetXYWW();
        Vector4 GetXZXX();
        Vector4 GetXZXY();
        Vector4 GetXZXZ();
        Vector4 GetXZXW();
        Vector4 GetXZYX();
        Vector4 GetXZYY();
        Vector4 GetXZYZ();
        Vector4 GetXZYW();
        Vector4 GetXZZX();
        Vector4 GetXZZY();
        Vector4 GetXZZZ();
        Vector4 GetXZZW();
        Vector4 GetXZWX();
        Vector4 GetXZWY();
        Vector4 GetXZWZ();
        Vector4 GetXZWW();
        Vector4 GetXWXX();
        Vector4 GetXWXY();
        Vector4 GetXWXZ();
        Vector4 GetXWXW();
        Vector4 GetXWYX();
        Vector4 GetXWYY();
        Vector4 GetXWYZ();
        Vector4 GetXWYW();
        Vector4 GetXWZX();
        Vector4 GetXWZY();
        Vector4 GetXWZZ();
        Vector4 GetXWZW();
        Vector4 GetXWWX();
        Vector4 GetXWWY();
        Vector4 GetXWWZ();
        Vector4 GetXWWW();
        Vector4 GetYXXX();
        Vector4 GetYXXY();
        Vector4 GetYXXZ();
        Vector4 GetYXXW();
        Vector4 GetYXYX();
        Vector4 GetYXYY();
        Vector4 GetYXYZ();
        Vector4 GetYXYW();
        Vector4 GetYXZX();
        Vector4 GetYXZY();
        Vector4 GetYXZZ();
        Vector4 GetYXZW();
        Vector4 GetYXWX();
        Vector4 GetYXWY();
        Vector4 GetYXWZ();
        Vector4 GetYXWW();
        Vector4 GetYYXX();
        Vector4 GetYYXY();
        Vector4 GetYYXZ();
        Vector4 GetYYXW();
        Vector4 GetYYYX();
        Vector4 GetYYYY();
        Vector4 GetYYYZ();
        Vector4 GetYYYW();
        Vector4 GetYYZX();
        Vector4 GetYYZY();
        Vector4 GetYYZZ();
        Vector4 GetYYZW();
        Vector4 GetYYWX();
        Vector4 GetYYWY();
        Vector4 GetYYWZ();
        Vector4 GetYYWW();
        Vector4 GetYZXX();
        Vector4 GetYZXY();
        Vector4 GetYZXZ();
        Vector4 GetYZXW();
        Vector4 GetYZYX();
        Vector4 GetYZYY();
        Vector4 GetYZYZ();
        Vector4 GetYZYW();
        Vector4 GetYZZX();
        Vector4 GetYZZY();
        Vector4 GetYZZZ();
        Vector4 GetYZZW();
        Vector4 GetYZWX();
        Vector4 GetYZWY();
        Vector4 GetYZWZ();
        Vector4 GetYZWW();
        Vector4 GetYWXX();
        Vector4 GetYWXY();
        Vector4 GetYWXZ();
        Vector4 GetYWXW();
        Vector4 GetYWYX();
        Vector4 GetYWYY();
        Vector4 GetYWYZ();
        Vector4 GetYWYW();
        Vector4 GetYWZX();
        Vector4 GetYWZY();
        Vector4 GetYWZZ();
        Vector4 GetYWZW();
        Vector4 GetYWWX();
        Vector4 GetYWWY();
        Vector4 GetYWWZ();
        Vector4 GetYWWW();
        Vector4 GetZXXX();
        Vector4 GetZXXY();
        Vector4 GetZXXZ();
        Vector4 GetZXXW();
        Vector4 GetZXYX();
        Vector4 GetZXYY();
        Vector4 GetZXYZ();
        Vector4 GetZXYW();
        Vector4 GetZXZX();
        Vector4 GetZXZY();
        Vector4 GetZXZZ();
        Vector4 GetZXZW();
        Vector4 GetZXWX();
        Vector4 GetZXWY();
        Vector4 GetZXWZ();
        Vector4 GetZXWW();
        Vector4 GetZYXX();
        Vector4 GetZYXY();
        Vector4 GetZYXZ();
        Vector4 GetZYXW();
        Vector4 GetZYYX();
        Vector4 GetZYYY();
        Vector4 GetZYYZ();
        Vector4 GetZYYW();
        Vector4 GetZYZX();
        Vector4 GetZYZY();
        Vector4 GetZYZZ();
        Vector4 GetZYZW();
        Vector4 GetZYWX();
        Vector4 GetZYWY();
        Vector4 GetZYWZ();
        Vector4 GetZYWW();
        Vector4 GetZZXX();
        Vector4 GetZZXY();
        Vector4 GetZZXZ();
        Vector4 GetZZXW();
        Vector4 GetZZYX();
        Vector4 GetZZYY();
        Vector4 GetZZYZ();
        Vector4 GetZZYW();
        Vector4 GetZZZX();
        Vector4 GetZZZY();
        Vector4 GetZZZZ();
        Vector4 GetZZZW();
        Vector4 GetZZWX();
        Vector4 GetZZWY();
        Vector4 GetZZWZ();
        Vector4 GetZZWW();
        Vector4 GetZWXX();
        Vector4 GetZWXY();
        Vector4 GetZWXZ();
        Vector4 GetZWXW();
        Vector4 GetZWYX();
        Vector4 GetZWYY();
        Vector4 GetZWYZ();
        Vector4 GetZWYW();
        Vector4 GetZWZX();
        Vector4 GetZWZY();
        Vector4 GetZWZZ();
        Vector4 GetZWZW();
        Vector4 GetZWWX();
        Vector4 GetZWWY();
        Vector4 GetZWWZ();
        Vector4 GetZWWW();
        Vector4 GetWXXX();
        Vector4 GetWXXY();
        Vector4 GetWXXZ();
        Vector4 GetWXXW();
        Vector4 GetWXYX();
        Vector4 GetWXYY();
        Vector4 GetWXYZ();
        Vector4 GetWXYW();
        Vector4 GetWXZX();
        Vector4 GetWXZY();
        Vector4 GetWXZZ();
        Vector4 GetWXZW();
        Vector4 GetWXWX();
        Vector4 GetWXWY();
        Vector4 GetWXWZ();
        Vector4 GetWXWW();
        Vector4 GetWYXX();
        Vector4 GetWYXY();
        Vector4 GetWYXZ();
        Vector4 GetWYXW();
        Vector4 GetWYYX();
        Vector4 GetWYYY();
        Vector4 GetWYYZ();
        Vector4 GetWYYW();
        Vector4 GetWYZX();
        Vector4 GetWYZY();
        Vector4 GetWYZZ();
        Vector4 GetWYZW();
        Vector4 GetWYWX();
        Vector4 GetWYWY();
        Vector4 GetWYWZ();
        Vector4 GetWYWW();
        Vector4 GetWZXX();
        Vector4 GetWZXY();
        Vector4 GetWZXZ();
        Vector4 GetWZXW();
        Vector4 GetWZYX();
        Vector4 GetWZYY();
        Vector4 GetWZYZ();
        Vector4 GetWZYW();
        Vector4 GetWZZX();
        Vector4 GetWZZY();
        Vector4 GetWZZZ();
        Vector4 GetWZZW();
        Vector4 GetWZWX();
        Vector4 GetWZWY();
        Vector4 GetWZWZ();
        Vector4 GetWZWW();
        Vector4 GetWWXX();
        Vector4 GetWWXY();
        Vector4 GetWWXZ();
        Vector4 GetWWXW();
        Vector4 GetWWYX();
        Vector4 GetWWYY();
        Vector4 GetWWYZ();
        Vector4 GetWWYW();
        Vector4 GetWWZX();
        Vector4 GetWWZY();
        Vector4 GetWWZZ();
        Vector4 GetWWZW();
        Vector4 GetWWWX();
        Vector4 GetWWWY();
        Vector4 GetWWWZ();
        Vector4 GetWWWW();
    };
}
